services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - XPACK_SECURITY_ENABLED=false
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_PASSWORD=elastic
      - INTERACTIVESETUP_ENABLED=false
    depends_on:
      - elasticsearch

  elasticsearch:
    build: 
      context: .
      dockerfile: Dockerfile
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=elastic
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - http.host=0.0.0.0
#      - http.port=9200
#      - "http.cors.allow-origin=http://localhost"
#      - "http.cors.enabled=true"
#      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
#      - "http.cors.allow-credentials=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch:/var/lib/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

volumes:
  opensearch:

networks:
  elastic: